name: Build VRL Server Image
on:
  workflow_dispatch:
  push:
    paths:
      - 'vrl-web-server-warp/**'
    branches:
      - main

permissions:
  contents: read  
  packages: write 


jobs:
  vrl-server-image-build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Container Image
        id: container_image_build
        run: |

              cd vrl-web-server-warp && \
              docker build -t vrl-web-server .

      - name: Push image to Github Registry
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

            CONTAINER_IMAGE_NAME="vrl-web-server"
            # As of now latest image tag will be used
            IMAGE_TAG="latest" && \
            GITHUB_CONTAINER_REGISTRY="docker.pkg.github.com" && \
            GH_REPO_ORG=$(echo $GITHUB_REPOSITORY | cut -f1 -d\/) && \
            GH_REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -f2 -d\/) && \
            GITHUB_CONTAINER_REPOSITORY_NAME="$GH_REPO_ORG/$GH_REPO_NAME/$CONTAINER_IMAGE_NAME" && \
            echo $GITHUB_TOKEN | docker login -u $GITHUB_ACTOR --password-stdin $GITHUB_CONTAINER_REGISTRY && \
            docker tag $CONTAINER_IMAGE_NAME $GITHUB_CONTAINER_REGISTRY/$GITHUB_CONTAINER_REPOSITORY_NAME:$IMAGE_TAG && \
            docker push $GITHUB_CONTAINER_REGISTRY/$GITHUB_CONTAINER_REPOSITORY_NAME:$IMAGE_TAG && \
            docker logout $GITHUB_CONTAINER_REGISTRY